#!/bin/bash
set -e

if [ "$TRAVIS_PULL_REQUEST" = "true" ] || [ "$TRAVIS_BRANCH" != "master" ]; then
  docker buildx build \
    --progress plain \
    --platform=linux/amd64,linux/arm/v7 \
    .
  exit $?
fi

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &> /dev/null
docker buildx build \
  --progress plain \
  --platform=linux/amd64,linux/arm/v7 \
  -t vulpemventures/nigiri-chopsticks:latest \
  --push \
  .