#!/bin/bash

set -e

case $1 in
  local) addr="localhost";;
  *) echo "Invalid option. Aborting."; exit 1;;
esac

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH

ADDR=$addr go test -v ./...

popd