#!/bin/bash

set -e

case $1 in
local) ci="false" ;;
ci) ci="true" ;;
*)
  echo "Specify a valid option via the CI environment variable. Aborting."
  exit 1
  ;;
esac

PARENT_PATH=$(dirname $(
  cd $(dirname $0)
  pwd -P
))

pushd $PARENT_PATH

CI=$ci go test -v ./...

popd
